### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by ajayabt** [ajayabt/prework-study-guide#1]
# HTML 

## User Story
As a boot camp student,
I want a Prework Study Guide website,
so that I can review all the information I learned throughout Prework.

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed
WHEN I view the study guide
THEN I see a dark blue header and footer, and four boxes with a shadow
WHEN I open the console in my browser
THEN I can see the four topics I learned listed along with a suggestion on what I should study first
WHEN I visit the website using the URL
THEN I can access my website from any browser

**Comment by soumytiwari** [comment]
so you want someone to make such website for you?

**Comment by ajayabt** [comment]
Hi,

I'm not sure what has happened here. I was following the steps for the
pre-course work and it seems to have sent you an email as a result?

Is this the only Issue number it sent?

Sorry for any confusion,

Ajaya

**Comment by soumytiwari** [comment]
aa.. no, thas fine... I was searching for issues on github and found yours.

**Comment by ajayabt** [comment]
Ah okay, I'm very new to this as you can probably tell!

Have a good day.

**Comment by soumytiwari** [comment]
yeah sure!

Have a good day you too :)
